---
    - name: Install zabbix-server and zabbix-web
      yum: name={{ item }} state=latest
      loop:
         - zabbix-server-mysql
         - zabbix-web-mysql
 
    - name: Import zabbix initial data(create.sql.gz)
#      shell: zcat create.sql.gz | /usr/bin/mysql -u{{ DBUser }} -p{{ DBPassword }} {{ DBName }}
#         chdir=/usr/share/doc/zabbix-server-mysql-{{ version }}/ 
      mysql_db:
         login_host: "localhost"
         login_user: "zabbix"
         login_password: "zabbix"
         login_port: "3306"
         name: "zabbix"
         target: "/usr/share/doc/zabbix-server-mysql-{{ version }}/create.sql.gz"
         state: "import"
   
    - name: Config php
      lineinfile:
         path: /etc/httpd/conf.d/zabbix.conf
         regexp: "{{ item.regexp }}"
         line: "{{ item.line }}"
      loop:
         - { regexp: '# php_value date.timezone', line: '       php_value date.timezone Asia/Shanghai'}

    - name: Copy /etc/zabbix/zabbix_server.conf files
      template: src=zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf owner=root group=root mode=644

    - name: Copy /etc/zabbix/web/zabbix.conf.php files
      template: src=zabbix.conf.php.j2 dest=/etc/zabbix/web/zabbix.conf.php owner=root group=root mode=644       

    - name: start zabbix-server and zabbix-web
      service: name={{ item }} state=started enabled=yes
      loop:
         - zabbix-server
         - httpd
